# Project Milestone 2: Dataset and Problem Approval
**Project Title:** Personalized Chess Opening Recommendations Using Machine Learning  
**Team Name:** Machine Learners (Team 66)
---

## 1. Data Source & License

* **Dataset Source:** [Lichess Open Database](https://database.lichess.org/)
* **Dataset Download Link:** [August 2016 Standard Rated Games](https://database.lichess.org/standard/lichess_db_standard_rated_2016-08.pgn.zst)
* **License:** Released into the public domain under the [Creative Commons CC0 1.0 Universal (CC0 1.0) Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/).
* **Usage & Rights:** The CC0 dedication waives all copyright rights worldwide. We have full permission to parse, clean, engineer features, store extracted tabular subsets, and distribute model artifacts for academic and non-commercial research purposes.

---

## 2. Data Card

* **Dataset Overview:** Contains chess game records from 6,483,257 standard rated games played on Lichess.org during August 2016.
* **Key Attributes Extracted:** Player Elo ratings (`WhiteElo`, `BlackElo`), match time control (`TimeControl`), opening identifiers (`ECO`, `Opening`), and game outcome (`Result`).
* **Target Audience & Purpose:** Used to train predictive models that estimate game outcome probabilities, which are then used by our recommendation system to give personalized opening advice to players based on their skill bracket.
* **Data Cleaning & Filtering:** High-cardinality metadata (`White`, `Black`, `Site`, `Event`, `Round`, `UTCTime`) and post-game leakage features (`WhiteRatingDiff`, `BlackRatingDiff`, `WhiteTitle`, `BlackTitle`) are removed prior to training.

---

## 3. Inputs, Outputs, and Task Definition

### Target & Task Definition
* **Machine Learning Task:** Supervised Multi-Class Classification.
* **Target Variable ($Y$):** `result` (Categorical outcome of the game).
  * `1` : White Win
  * `0` : Draw
  * `-1` : Black Win
* **Model Objective:** Estimate the conditional probability distribution $P(Y \mid X)$ across all three potential outcomes given player ratings, match conditions, and opening choices.
* **Downstream Application (Recommendation Engine):** The model takes user query inputs, evaluates candidate openings (`ECO` codes) through the trained classifier, and outputs a ranked list of openings that maximize the user's expected win/draw likelihood for their Elo tier.

### Sample Feature Vector ($X$) & Model Outputs ($Y$)
* **Model Input Feature Vector ($X$):**
  `[avg_elo=1450, elo_diff=35, time_control_class="Rapid", eco_code="C50", opening_draw_rate=0.22]`
* **Model Probabilistic Output ($Y$):**
  `[P(White Win)=0.54, P(Draw)=0.26, P(Black Win)=0.20]`

### User Interface Query Inputs
When a chess player uses the recommendation interface, they do not enter internal model features like `eco_code` or `elo_diff`. Instead, they enter:
1. `user_elo` (e.g., `1400`)
2. `time_control_class` (e.g., `"Rapid"`)
3. `playstyle_preference` (Optional: e.g., `"Tactical"`, `"Aggressive"`, or `"Solid"`)

---

In [ ]:
# Chess Reading Tools
!pip install python-chess zstandard -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 52.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for chess (setup.py) ... done

### **2.1 Import Dataset + Tools**

In [ ]:
import pandas as pd
import chess
import chess.pgn
import zstandard as zstd
import io



# file_path = "lichess_db_standard_rated_2014-08.pgn.zst"
file_path = "lichess_db_standard_rated_2016-08.pgn.zst"

rows = []

with open(file_path, "rb") as f:
    reader = zstd.ZstdDecompressor().stream_reader(f)
    text = io.TextIOWrapper(reader)

    for i in range(10000):
        game = chess.pgn.read_game(text)

        if game is None:
            break

        rows.append(dict(game.headers))

df = pd.DataFrame(rows)

### **2.2 Data Description**

In [ ]:
df.shape

(10000, 20)

In [ ]:
df.describe()

,Event,Site,Date,Round,White,Black,Result,UTCDate,UTCTime,WhiteElo,BlackElo,WhiteRatingDiff,BlackRatingDiff,ECO,Opening,TimeControl,Termination,Moves,BlackTitle,WhiteTitle
count,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,9971,9971,10000,10000,10000,10000,10000,10,9
unique,21,10000,1,1,2527,2507,3,2,8706,1170,1202,323,365,285,1074,212,2,9953,3,3
top,Rated Blitz game,https://lichess.org/zsOgh3Bn,????.??.??,?,nichiren1967,VEGETAL,1-0,2014.08.01,08:30:01,1500,1500,+8,-11,A00,Van't Kruijs Opening,300+0,Normal,1. g3 Nf6 2. Bg2 1-0,LM,LM
freq,3667,1,10000,10000,93,75,5080,7526,5,129,172,435,410,818,293,1888,6537,7,8,6

In [ ]:
df.isnull().sum()

Event                 0
Site                  0
Date                  0
Round                 0
White                 0
Black                 0
Result                0
UTCDate               0
UTCTime               0
WhiteElo              0
BlackElo              0
WhiteRatingDiff      29
BlackRatingDiff      29
ECO                   0
Opening               0
TimeControl           0
Termination           0
Moves                 0
BlackTitle         9990
WhiteTitle         9991
dtype: int64

In [ ]:
df[["ECO", "Opening"]].head(20)

    ECO                                            Opening
0   B06                          Robatsch (Modern) Defense
1   E61                   Indian Game: West Indian Defense
2   B20                                   Sicilian Defense
3   C41                                Philidor Defense #2
4   C11  French Defense: Classical Variation, Steinitz ...
5   A00                                   Gedult's Opening
6   A40                                       Queen's Pawn
7   C10                 French Defense: Marshall Variation
8   A03                      Bird Opening: Dutch Variation
9   C42                                   Petrov's Defense
10  A40           Englund Gambit Declined, Reversed French
11  C34            King's Gambit Accepted, MacLeod Defense
12  C00                 French Defense: Chigorin Variation
13  A45                                        Indian Game
14  C00                     French Defense: Queen's Knight
15  C61                          Ruy Lopez: Bird Variation
16  B01                               Scandinavian Defense
17  D06           Queen's Gambit Refused: Marshall Defense
18  C46               Four Knights Game: Italian Variation
19  A40                                    Horwitz Defense

In [ ]:
df["ECO"].value_counts()

ECO
A00    818
C00    577
A40    542
D00    445
B01    411
      ...
D52      1
E62      1
E15      1
A23      1
A83      1
Name: count, Length: 285, dtype: int64

In [ ]:
df["Event"].value_counts().head(20)

Event
Rated Blitz game                                                   3667
Rated Bullet game                                                  2950
Rated Classical game                                               2559
Rated Bullet tournament https://lichess.org/tournament/J5IS2eGz      68
Rated Blitz tournament https://lichess.org/tournament/SJvQgOQB       60
Rated Bullet tournament https://lichess.org/tournament/9kaBZUqu      60
Rated Blitz tournament https://lichess.org/tournament/EUz2QXQo       57
Rated Blitz tournament https://lichess.org/tournament/xUoiDG1y       57
Rated Blitz tournament https://lichess.org/tournament/WfihV96Y       56
Rated Blitz tournament https://lichess.org/tournament/3NXUIHPG       55
Rated Blitz tournament https://lichess.org/tournament/096JCUD0       54
Rated Blitz tournament https://lichess.org/tournament/qItJzOPy       50
Rated Blitz tournament https://lichess.org/tournament/1mgwlz7Q       49
Rated Blitz tournament https://lichess.org/tournament/4GCjTJ3H       49
Rated Bullet tournament https://lichess.org/tournament/wCuSBvN3      42
Rated Blitz tournament https://lichess.org/tournament/jUJXzBDq       37
Rated Blitz tournament https://lichess.org/tournament/Zq22Kbwb       35
Rated Bullet tournament https://lichess.org/tournament/ynuuY6jw      34
Rated Correspondence game                                            21
Rated Blitz tournament https://lichess.org/tournament/R8vL6P2Z       20
Name: count, dtype: int64

### **2.3 Data Cleaning**

#### **Dropped Fields:**
- Site
- Date
- Round
- White
- Black
- UTCTime
- WhiteRatingDiff
- BlackRatingDiff
- WhiteTitle
- BlackTitle

#### **Persistent Fields:**
1.   Event
2.   Result - W/L for who
3.   BlackElo
4.   ECO
5.   *Opening
6.   TimeControl (420 + 8 = 420s per player + 8s per turn)
7.   Termination
8.   Moves

***Note:** Opening and ECO represent the same thing, opening can be more accurate in some instances but is less consistent than ECO

In [ ]:
columns_to_drop = [
    "Site",
    "Date",
    "Round",
    "White",
    "Black",
    "UTCTime",
    "UTCDate",
    #"WhiteRatingDiff",
    "BlackRatingDiff", # White always goes first and every row has a rating for W/B (Not sure why you would need both?)
    "WhiteTitle",
    "BlackTitle"
]

dfclean = df.drop(columns=columns_to_drop)

dfclean.head(50)

,Event,Result,WhiteElo,BlackElo,WhiteRatingDiff,ECO,Opening,TimeControl,Termination,Moves
0,Rated Classical game,0-1,1407,1669,-5,B06,Robatsch (Modern) Defense,420+8,Time forfeit,1. e4 g6 2. d4 Bg7 3. c3 d6 4. Qf3 Nf6 5. h3 O...
1,Rated Blitz game,0-1,1382,1602,-5,E61,Indian Game: West Indian Defense,420+0,Time forfeit,1. d4 Nf6 2. c4 g6 3. a3 Bg7 4. Nf3 O-O 5. Nc3...
2,Rated Blitz game,1-0,1519,1306,+6,B20,Sicilian Defense,180+5,Normal,1. e4 c5 2. Qf3 e5 3. Bc4 Nf6 4. Nh3 h6 5. g4 ...
3,Rated Blitz game,0-1,1265,1623,-6,C41,Philidor Defense #2,300+0,Normal,1. e4 e5 2. Nf3 d6 3. Nc3 f5 4. exf5 Bxf5 5. d...
4,Rated Bullet game,1-0,1989,1872,+8,C11,"French Defense: Classical Variation, Steinitz ...",120+0,Normal,1. e4 e6 2. d4 d5 3. Nc3 Nf6 4. e5 Ne4 5. Nce2...
5,Rated Blitz game,0-1,1187,1230,-11,A00,Gedult's Opening,420+1,Normal,1. f3 e5 2. g4 d5 3. Bg2 d4 4. c4 dxc3 5. Nxc3...
6,Rated Bullet tournament https://lichess.org/to...,1-0,1760,1564,+6,A40,Queen's Pawn,0+1,Time forfeit,1. d4 c6 2. Nf3 d5 3. g3 Nf6 4. Bg2 e6 5. O-O ...
7,Rated Bullet game,0-1,1828,1747,-14,C10,French Defense: Marshall Variation,120+0,Time forfeit,1. e4 e6 2. d4 d5 3. Nc3 c5 4. exd5 exd5 5. dx...
8,Rated Bullet game,0-1,1949,1895,-12,A03,Bird Opening: Dutch Variation,120+0,Normal,1. f4 d5 2. Nf3 c5 3. e3 Bg4 4. Bb5+ Nd7 5. Bx...
9,Rated Classical game,0-1,1440,1648,-9,C42,Petrov's Defense,480+10,Normal,1. e4 e5 2. Nf3 Nf6 3. d3 Bc5 4. Be2 Nc6 5. c3...
10,Rated Blitz game,1-0,1634,1335,+4,A40,"Englund Gambit Declined, Reversed French",120+6,Normal,1. d4 e5 2. e3 e4 3. f4 d5 4. c3 Nf6 5. Nd2 Bg...
11,Rated Classical game,1-0,1352,1353,+13,C34,"King's Gambit Accepted, MacLeod Defense",360+3,Normal,1. e4 e5 2. f4 exf4 3. Nf3 Nc6 4. d4 Bb4+ 5. c...
12,Rated Blitz game,1-0,1862,1790,+51,C00,French Defense: Chigorin Variation,180+0,Time forfeit,1. e4 e6 2. Qe2 Nf6 3. d3 d5 4. e5 Nfd7 5. f4 ...
13,Rated Blitz game,0-1,1772,1999,-5,A45,Indian Game,180+0,Time forfeit,1. d4 Nf6 2. e3 g6 3. c3 Bg7 4. Nd2 d6 5. Ngf3...
14,Rated Blitz game,1-0,1571,1714,+14,C00,French Defense: Queen's Knight,300+0,Normal,1. e4 e6 2. Nc3 c6 3. d4 d5 4. f3 h6 5. Bd3 a6...
15,Rated Classical game,1-0,1489,1633,+16,C61,Ruy Lopez: Bird Variation,600+3,Normal,1. e4 e5 2. Nf3 Nc6 3. Bb5 Nd4 4. Nxe5 Nxb5 5....
16,Rated Bullet game,0-1,1477,1525,-9,B01,Scandinavian Defense,120+0,Time forfeit,1. e4 d5 2. e5 Bf5 3. d4 e6 4. Bd3 Bg6 5. Bxg6...
17,Rated Blitz game,0-1,1443,1652,-5,D06,Queen's Gambit Refused: Marshall Defense,420+1,Normal,1. d4 d5 2. c4 Nf6 3. Nc3 Bf5 4. cxd5 e6 5. a3...
18,Rated Blitz game,1-0,1163,1504,+23,C46,Four Knights Game: Italian Variation,300+0,Normal,1. e4 e5 2. Nf3 Nf6 3. Nc3 Nc6 4. Bc4 Nxe4 5. ...
19,Rated Blitz game,1-0,1601,1587,+10,A40,Horwitz Defense,300+0,Normal,1. d4 e6 2. Nf3 d5 3. Bg5 Be7 4. Bxe7 Nxe7 5. ...
20,Rated Bullet tournament https://lichess.org/to...,0-1,1610,1646,-12,A00,Van't Kruijs Opening,0+1,Time forfeit,1. e3 e6 2. d4 c6 3. c4 d5 4. cxd5 cxd5 5. e4 ...
21,Rated Blitz game,0-1,1333,1621,-3,C68,"Ruy Lopez: Exchange Variation, King's Bishop V...",120+3,Normal,1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Bxc6 dxc6 5. ...
22,Rated Bullet game,1-0,1356,1271,+10,A84,Dutch Defense: Normal Variation,60+0,Time forfeit,1. d4 f5 2. c4 Nf6 3. e3 g6 4. Nf3 Bg7 5. Nbd2...
23,Rated Blitz game,1-0,1864,1802,+9,A13,English Opening: Agincourt Defense,180+1,Time forfeit,1. c4 e6 2. Nc3 c5 3. Nf3 Nc6 4. d4 cxd4 5. Nx...
24,Rated Bullet game,0-1,1798,1798,-11,B01,Scandinavian Defense: Mieses-Kotroc Variation,60+0,Time forfeit,1. e4 d5 2. exd5 Qxd5 3. Nc3 Qd8 4. Bc4 c6 5. ...
25,Rated Blitz game,0-1,1516,1589,-9,B20,Sicilian Defense: Bowdler Attack,300+0,Normal,1. e4 c5 2. Bc4 d6 3. Nc3 g6 4. Nf3 Bg7 5. h3 ...
26,Rated Classical game,0-1,1631,1744,-8,C53,"Italian Game: Classical Variation, Giuoco Pian...",720+10,Time forfeit,1. e4 e5 2. Bc4 Nc6 3. c3 Nf6 4. d3 Bc5 5. Nf3...
27,Rated Blitz game,0-1,1462,1552,-9,C65,"Ruy Lopez: Berlin Defense, Beverwijk Variation",300+0,Normal,1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. O-O Bc5 5. d...
28,Rated Blitz game,1-0,1535,1645,+16,B52,"Sicilian Defense: Canal Attack, Main Line",300+0,Time forfeit,1. e4 c5 2. Nf3 d6 3. Bb5+ Bd7 4. Bxd7+ Qxd7 5...
29,Rated Blitz game,1-0,1870,1738,+8,B01,Scandinavian Defense: Mieses-Kotroc Variation,360+1,Time forfeit,1. e4 d5 2. exd5 Qxd5 3. Nf3 Qd8 4. Be2 e6 5. ...
30,Rated Blitz game,1-0,1639,1724,+34,B25,"Sicilian Defense: Closed Variation, Traditional",300+0,Normal,1. e4 c5 2. Nc3 Nc6 3. Nf3 e6 4. Bb5 a6 5. Be2...
31,Rated Bullet game,1-0,1883,1655,+21,A45,Trompowsky Attack,60+0,Time forfeit,1. d4 Nf6 2. Bg5 g6 3. Bxf6 exf6 4. h4 Bg7 5. ...
32,Rated Correspondence game,0-1,1454,1633,-6,D06,Queen's Gambit,-,Normal,1. d4 d5 2. c4 g6 3. Nc3 dxc4 4. Qa4+ Nd7 5. Q...
33,Rated Classical game,1-0,1323,1168,+7,B01,Scandinavian Defense,300+8,Normal,1. e4 d5 2. Nc3 d4 3. Nd5 e5 4. Nf3 f5 5. Nxe5...
34,Rated Blitz game,0-1,1500,1570,-12,C46,Three Knights Opening,240+0,Normal,1. e4 e5 2. Nf3 Nc6 3. Nc3 Be7 4. Bb5 d6 5. O-...
35,Rated Blitz game,1/2-1/2,1198,1201,+1,C48,Four Knights Game: Spanish Variation,180+1,Normal,1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. Nc3 d6 5. Bx...
36,Rated Bullet game,1-0,1118,1196,+60,A06,Zukertort Opening: Reversed Mexican Defense,60+0,Normal,1. Nf3 d5 2. Nc3 Be6 3. d4 c6 4. b4 Bg4 5. Qd3...
37,Rated Blitz game,1-0,1754,1518,+5,C35,"King's Gambit Accepted, Cunningham Defense",180+0,Normal,1. e4 e5 2. f4 exf4 3. Nf3 Be7 4. h4 d5 5. e5 ...
38,Rated Bullet game,0-1,1549,1951,-3,B06,Modern Defense,60+0,Normal,1. e4 g6 2. Nc3 Bg7 3. Nf3 e6 4. d4 Ne7 5. Bf4...
39,Rated Blitz game,1-0,1759,1778,+11,C44,Ponziani Opening: Jaenisch Counterattack,300+0,Normal,1. e4 e5 2. Nf3 Nc6 3. c3 Nf6 4. d3 d6 5. h3 B...
40,Rated Classical game,0-1,1241,1520,-33,C00,St. George Defense,180+8,Normal,1. d4 a6 2. e4 e6 3. e5 c5 4. c3 cxd4 5. Qxd4 ...
41,Rated Blitz tournament https://lichess.org/tou...,1-0,1870,1631,+5,B00,Owen Defense,300+0,Normal,1. e4 b6 2. d4 Bb7 3. Nc3 g6 4. Be3 Bg7 5. Qd2...
42,Rated Bullet game,1-0,2014,1972,+9,A01,Nimzo-Larsen Attack: Indian Variation,60+0,Time forfeit,1. b3 Nf6 2. Bb2 g6 3. e3 Bg7 4. c4 Nh5 5. Nc3...
43,Rated Blitz game,1-0,2039,1672,+3,B09,"Pirc Defense: Austrian Attack, Unzicker Attack",240+0,Normal,1. e4 d6 2. d4 Nf6 3. Nc3 g6 4. f4 Bg7 5. Nf3 ...
44,Rated Bullet game,1-0,1588,1544,+10,A01,Nimzo-Larsen Attack: English Variation,60+0,Time forfeit,1. b3 c5 2. g3 Nc6 3. Bg2 d5 4. f3 e5 5. e3 f5...
45,Rated Bullet game,1-0,1627,1662,+52,B01,Scandinavian Defense: Modern Variation #2,60+0,Normal,1. e4 d5 2. exd5 Nf6 3. Nc3 Nxd5 4. Nf3 Nc6 5....
46,Rated Blitz game,0-1,1787,1767,-11,C10,"French Defense: Rubinstein Variation, Fort Kno...",300+4,Normal,1. e4 e6 2. d4 d5 3. Nc3 dxe4 4. Nxe4 Bd7 5. N...
47,Rated Classical game,1-0,1417,1500,+9,D00,Queen's Pawn Game #2,900+8,Normal,1. d4 d5 2. e3 Nc6 3. c3 Nf6 4. h3 Bd7 5. Qf3 ...
48,Rated Bullet game,1-0,1743,1855,+15,D45,Semi-Slav Defense: Main Line,120+0,Normal,1. d4 d5 2. c4 c6 3. Nc3 e6 4. Nf3 Nf6 5. e3 B...
49,Rated Blitz game,1-0,1835,1846,+77,D31,Queen's Gambit Declined: Queen's Knight Variation,180+0,Normal,1. d4 d5 2. c4 e6 3. Nc3 dxc4 4. e3 c6 5. Bxc4...